# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [31]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [32]:
city_data_file = "city_data.csv"

city_df = pd.read_csv(city_data_file)
city_df.head()

,City ID,City,Cloudiness,Country,Date,Humidity,Lat,Long,Max Temp,Wind Speed
0,0,Mackay,40,AU,1600301117,73,-21.15,149.20,24.44,7.20
1,1,Isangel,40,VU,1600301117,57,-19.55,169.27,27.00,5.10
2,2,Busselton,0,AU,1600301117,72,-33.65,115.33,11.11,2.68
3,3,Ushuaia,40,AR,1600301052,64,-54.80,-68.30,4.00,8.20
4,4,Santiago del Estero,33,AR,1600301117,36,-27.80,-64.26,21.09,3.69

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [33]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [34]:
# Store 'Lat' and 'Lng' into  locations 
locations = city_df[["Lat", "Long"]].astype(float)

# Convert Humidity to float and store
# Drop NaN values 
city_df_drop = city_df.dropna()
humidity = city_df["Humidity"].astype(float)

In [35]:
# Create a humidity Heatmap layer
fig_heat = gmaps.figure()

humidity_heat = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig_heat.add_layer(humidity_heat)

fig_heat

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [45]:
city_df_drop

,City ID,City,Cloudiness,Country,Date,Humidity,Lat,Long,Max Temp,Wind Speed
0,0,Mackay,40,AU,1600301117,73,-21.15,149.20,24.44,7.20
1,1,Isangel,40,VU,1600301117,57,-19.55,169.27,27.00,5.10
2,2,Busselton,0,AU,1600301117,72,-33.65,115.33,11.11,2.68
3,3,Ushuaia,40,AR,1600301052,64,-54.80,-68.30,4.00,8.20
4,4,Santiago del Estero,33,AR,1600301117,36,-27.80,-64.26,21.09,3.69
...,...,...,...,...,...,...,...,...,...,...
556,556,Los Llanos de Aridane,96,ES,1600301192,83,28.66,-17.92,24.00,5.10
557,557,Hayden,1,US,1600301192,36,47.77,-116.79,26.67,4.10
558,558,‘Ewa Beach,1,US,1600301193,58,21.32,-158.01,32.00,5.10
559,559,Khovd,0,MN,1600301193,50,48.01,91.64,9.38,0.83
560,560,Yatou,97,CN,1600301193,63,37.15,122.38,18.76,2.74

In [47]:
cleaned_city_df = city_df_drop.loc[(city_df_drop['Cloudiness'] == 0) & (city_df_drop['Wind Speed'] < 7)]
cleaned_city_df_final = cleaned_city_df.loc[(cleaned_city_df['Max Temp'] > 0) & (cleaned_city_df['Max Temp'] <= 27)]
cleaned_city_df_final

,City ID,City,Cloudiness,Country,Date,Humidity,Lat,Long,Max Temp,Wind Speed
2,2,Busselton,0,AU,1600301117,72,-33.65,115.33,11.11,2.68
28,28,Beloha,0,MG,1600301121,93,-25.17,45.05,17.75,1.82
36,36,Turkmenabat,0,TM,1600301121,45,39.07,63.58,17.00,2.10
39,39,Bethel,0,US,1600300850,86,41.37,-73.41,16.67,2.94
67,67,Port Hedland,0,AU,1600301126,69,-20.32,118.57,26.00,4.60
95,95,Ismailia,0,EG,1600301130,91,30.60,32.27,23.47,1.65
99,99,Tortolì,0,IT,1600301130,60,39.93,9.66,23.00,6.20
106,106,Kristinehamn,0,SE,1600301131,65,59.31,14.11,9.00,5.10
109,109,Byron Bay,0,AU,1600301132,60,-28.65,153.62,22.78,1.00
124,124,Stary Krym,0,UA,1600301133,74,45.03,35.10,16.35,1.73
132,132,Kysyl-Syr,0,RU,1600301134,72,63.90,122.76,8.14,0.98
148,148,Marsá Maţrūḩ,0,EG,1600301136,78,31.35,27.25,25.00,1.43
155,155,Jalu,0,LY,1600301137,56,29.03,21.55,26.26,4.57
157,157,Mossamedes,0,AO,1600301137,72,-15.20,12.15,16.42,4.56
160,160,Assiut,0,EG,1600301138,54,27.18,31.18,26.00,2.10
191,191,Ust-Maya,0,RU,1600301141,60,60.42,134.53,9.29,1.43
194,194,Carnarvon,0,AU,1600301142,59,-24.87,113.63,16.00,5.10
211,211,Rodolfo Sánchez Taboada,0,MX,1600301144,70,31.72,-116.57,25.56,0.89
216,216,Manosque,0,FR,1600301146,94,43.83,5.79,15.56,2.04
231,231,Linköping,0,SE,1600301147,65,58.41,15.62,8.89,5.10
234,234,Constitución,0,CL,1600301148,86,-35.33,-72.42,11.92,5.62
240,240,Nelson Bay,0,AU,1600301148,49,-32.72,152.15,25.00,5.70
246,246,Asău,0,RO,1600301150,87,46.43,26.40,13.33,1.62
255,255,Ararat,0,AM,1600301151,43,39.83,44.70,22.00,2.10
263,263,Maxixe,0,MZ,1600301152,92,-23.86,35.35,21.62,3.71
281,281,Batī,0,ET,1600301155,52,11.18,40.02,20.91,1.89
282,282,Kumul,0,CN,1600301155,30,42.80,93.45,16.62,1.18
284,284,Camacupa,0,AO,1600301155,71,-12.02,17.48,16.54,0.15
288,288,Ballina,0,AU,1600301156,60,-28.87,153.57,22.78,1.00
295,295,Korla,0,CN,1600301157,77,41.76,86.15,20.00,3.52
297,297,Kargil,0,IN,1600301157,57,34.57,76.10,7.77,2.04
316,316,Tāybād,0,IR,1600301160,36,34.74,60.78,16.66,5.34
319,319,Bāfq,0,IR,1600301160,29,31.61,55.41,16.68,1.06
324,324,Ibrā’,0,OM,1600301160,66,22.69,58.53,24.40,0.98
326,326,Nouadhibou,0,MR,1600301161,74,20.93,-17.03,26.00,5.10
340,340,Malokaterynivka,0,UA,1600301162,62,47.65,35.25,15.00,2.00
349,349,Centralina,0,BR,1600301164,33,-18.58,-49.20,26.07,3.32
352,352,Almaznyy,0,RU,1600301164,46,48.04,40.05,12.00,3.00
356,356,Yazd,0,IR,1600301165,25,31.90,54.37,19.00,0.81
361,361,Antsohihy,0,MG,1600301165,79,-14.88,47.99,17.40,1.72
377,377,Burns Lake,0,CA,1600301167,43,54.23,-125.75,21.03,1.61
431,431,Fort Saint James,0,CA,1600301176,49,54.43,-124.25,20.69,1.65
439,439,Angoche,0,MZ,1600301177,84,-16.23,39.91,22.45,4.23
443,443,Clarence Town,0,AU,1600301178,49,-32.58,151.78,25.00,5.70
465,465,Mafeteng,0,LS,1600301181,50,-29.82,27.24,5.85,0.29
474,474,Kultuk,0,RU,1600301182,65,51.72,103.70,8.19,1.91
485,485,Inhambane,0,MZ,1600301183,91,-23.86,35.38,21.99,4.13
492,492,Chase,0,CA,1600301184,56,50.82,-119.69,24.44,1.45
498,498,Ampanihy,0,MG,1600301185,86,-24.70,44.75,18.43,1.87
507,507,Bay Roberts,0,CA,1600301186,59,47.60,-53.26,10.00,4.47
508,508,Murgab,0,TM,1600301186,45,37.50,61.97,20.00,2.10
518,518,Aksu,0,CN,1600301187,35,41.12,80.26,17.01,0.42
529,529,Alghero,0,IT,1600301189,100,40.56,8.32,19.00,0.50
530,530,Nizhniy Baskunchak,0,RU,1600301189,55,48.22,46.83,11.04,3.14
540,540,Yerbogachën,0,RU,1600301190,72,61.28,108.01,8.08,0.81
543,543,Vicuña,0,CL,1600301191,82,-30.03,-70.71,13.00,3.60
559,559,Khovd,0,MN,1600301193,50,48.01,91.64,9.38,0.83

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [49]:
hotel_df = pd.DataFrame(cleaned_city_df_final)
hotel_df['Hotel Name'] = ""

In [52]:
hotel_df.head()

,City ID,City,Cloudiness,Country,Date,Humidity,Lat,Long,Max Temp,Wind Speed,Hotel Name
2,2,Busselton,0,AU,1600301117,72,-33.65,115.33,11.11,2.68,
28,28,Beloha,0,MG,1600301121,93,-25.17,45.05,17.75,1.82,
36,36,Turkmenabat,0,TM,1600301121,45,39.07,63.58,17.00,2.10,
39,39,Bethel,0,US,1600300850,86,41.37,-73.41,16.67,2.94,
67,67,Port Hedland,0,AU,1600301126,69,-20.32,118.57,26.00,4.60,

In [87]:
hotel_name = []

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "international hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify hotels
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Long"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Hotel" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
#         hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
        hotel_name.append(name_address["results"][0]["name"])

    except (KeyError, IndexError):
        hotel_name.append(np.nan)

In [92]:
hotel_df.dropna().head(20)

,City ID,City,Cloudiness,Country,Date,Humidity,Lat,Long,Max Temp,Wind Speed,Hotel Name
2,2,Busselton,0,AU,1600301117,72,-33.65,115.33,11.11,2.68,Abbey Beach Resort
36,36,Turkmenabat,0,TM,1600301121,45,39.07,63.58,17.00,2.10,Hotel Yupek Yoly (Silk Way)
39,39,Bethel,0,US,1600300850,86,41.37,-73.41,16.67,2.94,Hampton Inn Danbury
67,67,Port Hedland,0,AU,1600301126,69,-20.32,118.57,26.00,4.60,The Esplanade Hotel
95,95,Ismailia,0,EG,1600301130,91,30.60,32.27,23.47,1.65,Tolip Alforsan Island Hotel And Spa
99,99,Tortolì,0,IT,1600301130,60,39.93,9.66,23.00,6.20,Hotel La Bitta
106,106,Kristinehamn,0,SE,1600301131,65,59.31,14.11,9.00,5.10,Sockerslottet Hotell
109,109,Byron Bay,0,AU,1600301132,60,-28.65,153.62,22.78,1.00,Byron Bay Hotel and Apartments - Boutique Acco...
148,148,Marsá Maţrūḩ,0,EG,1600301136,78,31.35,27.25,25.00,1.43,Air Force hotel
157,157,Mossamedes,0,AO,1600301137,72,-15.20,12.15,16.42,4.56,iu Hotel Namibe
160,160,Assiut,0,EG,1600301138,54,27.18,31.18,26.00,2.10,Assiut hotels Armed Forces
194,194,Carnarvon,0,AU,1600301142,59,-24.87,113.63,16.00,5.10,Hospitality Carnarvon
216,216,Manosque,0,FR,1600301146,94,43.83,5.79,15.56,2.04,"Hôtel Le Pré Saint Michel - Manosque, Luberon"
231,231,Linköping,0,SE,1600301147,65,58.41,15.62,8.89,5.10,Hilma Winblads Bed and Breakfast
234,234,Constitución,0,CL,1600301148,86,-35.33,-72.42,11.92,5.62,Hotel Playa El Cable
240,240,Nelson Bay,0,AU,1600301148,49,-32.72,152.15,25.00,5.70,Oaks Pacific Blue Resort
246,246,Asău,0,RO,1600301150,87,46.43,26.40,13.33,1.62,Pensiunea Sophia
255,255,Ararat,0,AM,1600301151,43,39.83,44.70,22.00,2.10,B&B Sunrise House Aygavan
263,263,Maxixe,0,MZ,1600301152,92,-23.86,35.35,21.62,3.71,Sanny Motel
282,282,Kumul,0,CN,1600301155,30,42.80,93.45,16.62,1.18,China Telecom

In [96]:
hotel_df.to_csv("hotel_data.csv", encoding="utf-8")

In [97]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Long"]]

In [100]:
# Add marker layer ontop of heat map

# Convert hotel name to list
hotel_name_list = hotel_df["Hotel Name"].tolist()

# Create bank symbol layer
hotel_name_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=[f"Hotel Names: {hotel}" for hotel in hotel_name_list]
)


fig = gmaps.figure()
fig.add_layer(hotel_name_list)

# Display figure
fig

TraitError: Element of the 'layers' trait of a Map instance must be a Widget, but a value of ['Abbey Beach Resort', nan, 'Hotel Yupek Yoly (Silk Way)', 'Hampton Inn Danbury', 'The Esplanade Hotel', 'Tolip Alforsan Island Hotel And Spa', 'Hotel La Bitta', 'Sockerslottet Hotell', 'Byron Bay Hotel and Apartments - Boutique Accommodation', nan, nan, 'Air Force hotel', nan, 'iu Hotel Namibe', 'Assiut hotels Armed Forces', nan, 'Hospitality Carnarvon', nan, 'Hôtel Le Pré Saint Michel - Manosque, Luberon', 'Hilma Winblads Bed and Breakfast', 'Hotel Playa El Cable', 'Oaks Pacific Blue Resort', 'Pensiunea Sophia', 'B&B Sunrise House Aygavan', 'Sanny Motel', nan, 'China Telecom', nan, 'Ramada Hotel & Suites by Wyndham Ballina Byron', 'Kangcheng Jian Guo International Hotel', 'Hotel International Residency', nan, nan, 'Ibra Hotel', 'Hôtel Sahel', nan, 'MM Plaza Hotel', 'Gostinitsa Zverevo', 'Dad Hotel', nan, 'Key-oh Lodge', 'The View Hotel', nan, 'Erringhi Hotel', nan, 'Байкальский Рай', 'Sanny Motel', 'Jade Mountain Motel', nan, 'The Bayside Bed and Breakfast', nan, 'Tianyuan International Hotel', 'Villa Las Tronas', 'Arman hotel', nan, 'Hostal Aldea del Elqui', 'Steppe hotel'] <class 'list'> was specified.